# Generated by Django 2.2.6 on 2019-10-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191023_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountprofile',
            old_name='group',
            new_name='groups',
        ),
    ]
