# Generated by Django 2.2.6 on 2019-10-23 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='country')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('code', models.CharField(default='', max_length=3, verbose_name='code')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('code', models.CharField(default='', max_length=3, verbose_name='code')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='accounts.Country')),
                ('departments', models.ManyToManyField(blank=True, related_name='office_departments', to='accounts.Department')),
            ],
            options={
                'verbose_name': 'office',
                'verbose_name_plural': 'offices',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('level', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='city')),
                ('abbreviation', models.CharField(default='', max_length=3, verbose_name='abbreviation')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='accounts.Country')),
                ('offices', models.ManyToManyField(blank=True, related_name='city_offices', to='accounts.Office')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_password_change', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('cell', models.CharField(blank=True, default='', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.City')),
                ('department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Department')),
                ('group', models.ManyToManyField(blank=True, related_name='accountprofile_group', to='auth.Group')),
                ('level', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Level')),
                ('office', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accountprofile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
