# Generated by Django 2.2.6 on 2019-11-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191027_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='office',
            name='code',
        ),
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(default='', max_length=3, verbose_name='abbreviation'),
        ),
        migrations.AddField(
            model_name='office',
            name='abbreviation',
            field=models.CharField(default='', max_length=3, verbose_name='abbreviation'),
        ),
    ]
