# Generated by Django 2.2.6 on 2019-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20191102_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(),
        ),
    ]
