# Generated by Django 2.2.6 on 2019-10-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0004_auto_20191023_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='mem_priority',
            field=models.CharField(choices=[('Very Urgent', 'Very Urgent'), ('Moderate', 'Moderate'), ('Normal', 'Normal')], default='Normal', max_length=15, verbose_name='memo priority'),
        ),
    ]
