# Generated by Django 2.2.6 on 2019-10-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0007_memoattachment_memocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoattachment',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoattachment_attachment', to='memos.Memo'),
        ),
    ]
