# Generated by Django 2.2.6 on 2019-10-23 08:32

import apps.memos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='is open')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_sent', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date sent')),
                ('reference_number', models.CharField(db_index=True, max_length=23, unique=True, verbose_name='reference number')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('message', models.TextField()),
                ('memo_type', models.CharField(choices=[(1, 'Public'), (2, 'Private')], default=1, max_length=10, verbose_name='memo type')),
                ('mem_priority', models.CharField(choices=[(1, 'Very Urgent'), (2, 'Moderate'), (3, 'Normal')], default=3, max_length=15, verbose_name='memo priority')),
                ('commenting_required', models.BooleanField(default=True, verbose_name='commenting required')),
                ('receptors', models.ManyToManyField(blank=True, related_name='memo_receptors', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='memo_recipients', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memo_from', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memo_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'memo',
                'verbose_name_plural': 'memos',
                'ordering': ['-created'],
                'permissions': (('add_comment', 'Comment Memo'),),
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('date_archived', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date archived')),
                ('archiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memos.Memo')),
            ],
            options={
                'verbose_name': 'archive',
                'verbose_name_plural': 'archives',
            },
        ),
    ]
