# Generated by Django 2.2.6 on 2019-10-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0003_auto_20191023_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo_type',
            field=models.CharField(choices=[('PUB', 'Public'), ('PVT', 'Private')], default='PUB', max_length=10, verbose_name='memo type'),
        ),
    ]
