# Generated by Django 2.2.6 on 2019-10-25 18:28

import apps.shared.mptt
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0008_auto_20191025_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoattachment',
            options={'get_latest_by': ['timestamp']},
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='file',
            field=models.FileField(blank=True, help_text='Attach File', upload_to=apps.shared.mptt.AbstractAttachment.file_upload_to_dispatcher, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='file_name',
            field=models.CharField(default=1, max_length=255, verbose_name='file name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memoattachment_file_attachment', to='memos.MemoAttachment'),
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
