# Generated by Django 2.2.6 on 2019-11-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0009_auto_20191025_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memocomment',
            options={'get_latest_by': ['timestamp'], 'verbose_name': 'memo comment', 'verbose_name_plural': 'memo comments'},
        ),
    ]
