# Generated by Django 2.2.6 on 2019-10-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
    ]
